server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sreejathagirancha/config-server.git
          clone-on-start: true
          force-pull: true
          default-label: main